### PR TITLE
handle timeout error rather than crashing the scheduler

### PR DESCRIPTION
**Pull request by kimyen**
This change is ported from Apache/airflow 2.0: https://github.com/apache/airflow/blob/master/airflow/executors/kubernetes_executor.py#L102
This change fixes the timeout error that crashes the scheduler pod: https://github.com/github/data/issues/476#issuecomment-820753833

### CODE REVIEW

**Review by tbries — APPROVED** [review]
LGTM

**Comment by kimyen** [comment]
Deployed to prod and observed:
```
[2021-04-20 16:52:08 +0000] {kubernetes_executor.py:346} WARNING - There was a timeout error accessing the Kube API. Retrying request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 666, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 598, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/executors/kubernetes_executor.py", line 342, in run
    self.worker_uuid, self.kube_config)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/executors/kubernetes_executor.py", line 372, in _run
    **kwargs):
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 159, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 56, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='10.0.0.1', port=443): Read timed out.
```
The warning is what we want to see. However, we still see the stacktrace for timeout. And the pod did restart. It looks like ~~we didn't catch all exceptions.~~ the exception was "caught" twice. 🤔

**Comment by kimyen** [comment]
Deployed to prod and I see similar output as above. Looking more into it, `exc_info=True` cause the exception to be printed. However, the scheduler were not restarted. 
This doesn't help with the heart beat because it cause the scheduler to stay in this look for another 10s, and while in this loop the scheduler does not emit heartbeat.

**Comment by kimyen** [comment]
We went over 24hrs without an alerts about scheduler heartbeat. I will call this good and merge.

**Pull request merged**
